server:
  port: 8081
spring:
  data:
    mongodb:
      uri: mongodb://test:test123@mongo:27017/assignment?authSource=admin
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: order-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
logging:
  file:
    name: logs/app-prod.log
  level:
    org.springdoc: info
management:
  endpoints:
    web:
      exposure:
        include: health, info
  server:
    port: 8082
springdoc:
  swagger-ui:
    configUrl: "/order/api/v1/api-docs/swagger-config"
    url: "/order/api/v1/api-docs"