spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: assignment
  mvc:
    servlet:
      path: /api/v1
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
    filter: true
    display-request-duration: true
    default-model-expand-depth: 2
    default-model-rendering: example
    doc-expansion: none # Options: list, full, none
  api-docs:
    path: /api-docs

logging:
  level:
    org.springdoc: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"