spring:
  profiles:
    active: dev
  application:
    name: order-service
  mvc:
    servlet:
      path: /api/v1
springdoc:
  swagger-ui:
    enabled: true
#    path: /swagger-ui/index.html
    filter: true
    display-request-duration: true
    default-model-expand-depth: 2
    default-model-rendering: example
    doc-expansion: none # Options: list, full, none
  api-docs:
    path: /api-docs
